-- Отключить RLS (Row Level Security) на всех таблицах
-- Выполнить после 001_init.sql
ALTER TABLE bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE booking_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE games_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE telegram_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE admins DISABLE ROW LEVEL SECURITY;
ALTER TABLE pricing DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE time_slots DISABLE ROW LEVEL SECURITY;
